language: node_js
node_js:
- "node"

branches:
  only:
  - master

cache:
  directories:
  - node_modules

install:
- "npm install"
- "npm install codecov -g"

script:
- "npm run lint"
- "npm run test"
- "npm run build"
- "npm run build-docs"

after_success:
- "codecov"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs-dist
  on:
    branch: master
